services:
  postgres:
    container_name: postgres-logical
    # image: postgres:14
    # image: ubuntu:22.04
    build:
      context: ./
      dockerfile: ./Dockerfile
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=password
    command:
      - "postgres"
      - "-c"
      - "wal_level=logical"
    # command: /bin/sleep 600000

  clickhouse:
    container_name: clickhouse
    image: clickhouse/clickhouse-server:23.3.8.21
    ports:
      - 9000:9000
      - 8123:8123
      - 9009:9009
